// Labelled demo data. In Feature 2+ this shape moves to Supabase tables
// (profiles, posts). Keep field names snake_case to match the future schema.
//
// Optional post fields, omitted when unused:
//   image_url     string, attached image (local /demo/* here, Cloudinary URL when live)
//   link_preview  { url, title, site, description, image|null }
// Seed text is English-only. `lang` + `summary_en` stay in the schema because
// live posts in other languages still get an AI English summary.

export const PROFILES = [
  // ---- Mentors / seniors ----
  {
    id: "p1",
    name: "Sarah Chen",
    handle: "sarahc",
    role: "mentor",
    course: "CS",
    year: null, // graduated
    verified: true,
    skills: ["python", "algorithms", "interviews", "distributed-systems"],
    goals: [],
    outcome: "Software Engineer at Google (graduated 2024)",
    units: [
      { code: "SIT102", name: "Introduction to Programming", tip: "Do every lab twice. The exam is the labs in disguise." },
      { code: "SIT232", name: "Object-Oriented Development", tip: "Build the custom project early, don't leave it to week 11." },
      { code: "SIT215", name: "Computational Intelligence", tip: "The search and learning pracs are 80% of the learning. Start week 1." },
    ],
    resources: [
      { label: "NeetCode 150 (YouTube)", url: "https://www.youtube.com/@NeetCode", type: "YouTube" },
      { label: "Grokking Algorithms", url: "https://www.manning.com/books/grokking-algorithms", type: "Book" },
    ],
    is_demo: true,
  },
  {
    id: "p2",
    name: "Duc Tran",
    handle: "ductran",
    role: "mentor",
    course: "CS",
    year: 3,
    verified: true,
    skills: ["java", "data-structures", "tutoring", "interviews"],
    goals: [],
    outcome: "Tutor at Deakin, incoming intern at Atlassian",
    units: [
      { code: "SIT102", name: "Introduction to Programming", tip: "C++ with SplashKit in trimester 1 surprises people. Trust the process." },
      { code: "SIT232", name: "Object-Oriented Development", tip: "Learn the design patterns lectures properly, they come back in year 3." },
    ],
    resources: [
      { label: "Java MOOC (University of Helsinki)", url: "https://java-programming.mooc.fi/", type: "Course" },
    ],
    is_demo: true,
  },
  {
    id: "p3",
    name: "Priya Sharma",
    handle: "priyash",
    role: "mentor",
    course: "Data Science",
    year: null,
    verified: true,
    skills: ["sql", "pandas", "statistics", "tableau"],
    goals: [],
    outcome: "Data Analyst at Canva (graduated 2025)",
    units: [
      { code: "SIT191", name: "Introduction to Statistics and Data Analysis", tip: "Redo every workshop exercise in Python afterwards and it clicks." },
      { code: "SIT103", name: "Database Fundamentals", tip: "SQL joins on paper before touching the keyboard." },
    ],
    resources: [
      { label: "Mode SQL Tutorial", url: "https://mode.com/sql-tutorial", type: "Website" },
      { label: "StatQuest (YouTube)", url: "https://www.youtube.com/@statquest", type: "YouTube" },
    ],
    is_demo: true,
  },
  {
    id: "p4",
    name: "James Wilson",
    handle: "jamesw",
    role: "mentor",
    course: "Business",
    year: 3,
    verified: true,
    skills: ["accounting", "excel", "case-competitions", "networking"],
    goals: [],
    outcome: "PwC summer vacationer 2026",
    units: [
      { code: "MAA103", name: "Accounting for Decision Making", tip: "The group assignment carries the unit. Pick your team fast." },
      { code: "MIS171", name: "Business Analytics", tip: "Learn pivot tables before the first workshop." },
    ],
    resources: [
      { label: "Corporate Finance Institute free courses", url: "https://corporatefinanceinstitute.com/", type: "Course" },
    ],
    is_demo: true,
  },
  {
    id: "p5",
    name: "Linh Nguyen",
    handle: "linhng",
    role: "mentor",
    course: "IT",
    year: null,
    verified: true,
    skills: ["javascript", "react", "css", "portfolio"],
    goals: [],
    outcome: "Frontend Developer at a Melbourne startup (graduated 2025)",
    units: [
      { code: "SIT111", name: "Computer Systems", tip: "Your first real website. Make it something you'd show an employer." },
      { code: "SIT120", name: "Introduction to Responsive Web Apps", tip: "This unit IS your portfolio if you take it seriously." },
    ],
    resources: [
      { label: "The Odin Project", url: "https://www.theodinproject.com/", type: "Website" },
      { label: "Josh Comeau CSS course", url: "https://www.joshwcomeau.com/", type: "Website" },
    ],
    is_demo: true,
  },
  {
    id: "p6",
    name: "Ahmed Hassan",
    handle: "ahmedh",
    role: "mentor",
    course: "Design",
    year: 3,
    verified: true,
    skills: ["figma", "ux-research", "portfolio", "prototyping"],
    goals: [],
    outcome: "UX intern at REA Group",
    units: [
      { code: "ADD105", name: "Design Fundamentals", tip: "Document your process obsessively. The folio is the grade." },
      { code: "ADT202", name: "Web and Interface Design", tip: "Interview real users, not your friends pretending to be users." },
    ],
    resources: [
      { label: "Figma Learn", url: "https://www.figma.com/resource-library/", type: "Website" },
      { label: "NNGroup articles", url: "https://www.nngroup.com/articles/", type: "Website" },
    ],
    is_demo: true,
  },
  // ---- Mentees / current students ----
  {
    id: "p7",
    name: "Minh Le",
    handle: "minhle",
    role: "mentee",
    course: "IT",
    year: 1,
    verified: true,
    skills: ["html", "python"],
    goals: ["internship", "web-development"],
    outcome: null,
    units: [
      { code: "SIT102", name: "Introduction to Programming", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p8",
    name: "Lan Pham",
    handle: "lanpham",
    role: "mentee",
    course: "Business",
    year: 2,
    verified: false,
    skills: ["excel", "presentations"],
    goals: ["exchange", "consulting"],
    outcome: null,
    units: [
      { code: "MAA103", name: "Accounting for Decision Making", tip: null },
      { code: "MMK101", name: "Marketing Fundamentals", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p9",
    name: "Tom Baker",
    handle: "tombaker",
    role: "mentee",
    course: "CS",
    year: 1,
    verified: true,
    skills: ["python", "unity"],
    goals: ["game-development", "internship"],
    outcome: null,
    units: [
      { code: "SIT102", name: "Introduction to Programming", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p10",
    name: "Aisha Khan",
    handle: "aishak",
    role: "mentee",
    course: "Data Science",
    year: 2,
    verified: true,
    skills: ["python", "sql", "pandas"],
    goals: ["kaggle", "analyst-internship"],
    outcome: null,
    units: [
      { code: "SIT191", name: "Introduction to Statistics and Data Analysis", tip: null },
      { code: "SIT103", name: "Database Fundamentals", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p11",
    name: "Chris Park",
    handle: "chrisp",
    role: "mentee",
    course: "IT",
    year: 2,
    verified: false,
    skills: ["networking", "linux"],
    goals: ["cybersecurity", "certifications"],
    outcome: null,
    units: [
      { code: "SIT202", name: "Computer Networks and Communication", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p12",
    name: "Emma Davis",
    handle: "emmad",
    role: "mentee",
    course: "Design",
    year: 1,
    verified: true,
    skills: ["figma"],
    goals: ["portfolio", "ui-design"],
    outcome: null,
    units: [
      { code: "ADD105", name: "Design Fundamentals", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  // ---- Marketing mentors (current students) ----
  {
    id: "p13",
    name: "Hannah Vo",
    handle: "hannahvo",
    role: "mentor",
    course: "Business",
    year: 3,
    verified: true,
    skills: ["marketing", "consumer-behaviour", "presentations", "canva"],
    goals: [],
    outcome: "Marketing intern at a Melbourne skincare brand",
    units: [
      { code: "MMK101", name: "Marketing Fundamentals", tip: "Learn the 4Ps with real brands you already buy from. It sticks." },
    ],
    resources: [
      { label: "HubSpot Academy (free)", url: "https://academy.hubspot.com/", type: "Course" },
    ],
    is_demo: true,
  },
  {
    id: "p14",
    name: "Ryan Mitchell",
    handle: "ryanm",
    role: "mentor",
    course: "Business",
    year: 2,
    verified: true,
    skills: ["digital-marketing", "social-media", "analytics", "copywriting"],
    goals: [],
    outcome: "Part-time social media coordinator at a creative agency",
    units: [
      { code: "MMK101", name: "Marketing Fundamentals", tip: "The case study report is won in the research, not the writing." },
    ],
    resources: [],
    is_demo: true,
  },
];

// Personas available in the demo switcher (subset of profiles).
export const PERSONA_IDS = ["p8", "p7", "p10", "p13", "p2", "p1"];

const RAW_POSTS = [
  // ---- Featured long posts: showcase the AI summary, each has a photo and a
  // link, and each is tuned to rank first in For you for one demo persona ----
  {
    id: "f1",
    author_id: "p4",
    lang: "en",
    text: "Year 2 Business students keep asking me whether they have to choose between going on exchange and landing a consulting vacation program. You don't, but you need to plan backwards from the deadlines, not forwards from your wishes. Here is exactly what I did. February of year 2: applied for the PwC summer vacationer program while also shortlisting three exchange universities. Most people think these clash, but vacation programs run over the Australian summer and most northern hemisphere exchange semesters start in August or September, so you can do both in the same year. March: booked a meeting with the Deakin Abroad team and mapped my core units. MAA103 was the one that almost blocked me because the host uni had no direct equivalent, so I got it approved as an elective and took it at home first. That single meeting saved me a whole trimester. May to July: interviews. Every behavioural question I got had a better answer because I could talk about why I chose my exchange university and how I would use it. Consulting firms love anyone who has had to adapt quickly in a new country. Finally, budget. The OS-HELP loan covered my flights and first month of rent, and the vacation program pay covered the rest. Start the paperwork now, it is slower than any interview.",
    tldr: "Exchange and a consulting vacation program fit in the same year if you plan backwards from deadlines: apply in February, map units like MAA103 with Deakin Abroad early, use the exchange story in interviews, and fund it with OS-HELP plus program pay.",
    summary_en: null,
    image_url: "https://picsum.photos/id/0/1200/675",
    link_preview: {
      url: "https://www.deakin.edu.au/students",
      title: "Deakin Students",
      site: "deakin.edu.au",
      description: "Official student hub for units, support, study abroad and key dates.",
      image: null,
    },
    tags: ["exchange", "consulting", "internship", "planning"],
    unit_codes: ["MAA103"],
    topic: "careers",
    helpful_count: 118,
    hours_ago: 1,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "f2",
    author_id: "p3",
    lang: "en",
    text: "My full path from SIT103 to an analyst internship, for anyone in year 2 Data Science who feels behind. In SIT103 I treated every SQL lab like a mini portfolio piece: I saved the queries in a GitHub repo with a short README explaining the question each one answers. Boring, but recruiters opened that repo more than anything else I linked. Over the break I did the free Kaggle Learn courses on pandas and data cleaning. They take a weekend each and they fill exactly the gaps SIT191 leaves. Then I picked ONE finished Kaggle competition, a retail sales forecast, and spent three weeks on it. I did not care about the leaderboard. I cared about writing a clear notebook: what the data looked like, what I cleaned and why, which features mattered, and what I would try next. That notebook became the centre of every interview. Two interviewers literally opened it and asked me to walk through a cell. The SQL questions in the technical round were the same joins and window functions I had practised in SIT103. If you only do one thing this trimester: make your SQL labs public and write one honest Kaggle notebook. Depth beats a long list of certificates.",
    tldr: "Make your SIT103 SQL labs a public portfolio, fill the pandas gap with free Kaggle Learn courses, and write one clear notebook for a finished competition. That notebook and those SQL basics carried the analyst interviews.",
    summary_en: null,
    image_url: "https://picsum.photos/id/60/1200/675",
    link_preview: {
      url: "https://www.kaggle.com/learn",
      title: "Kaggle Learn: free micro-courses",
      site: "kaggle.com",
      description: "Short hands-on courses in Python, pandas, SQL, data cleaning and machine learning.",
      image: null,
    },
    tags: ["kaggle", "analyst-internship", "sql", "pandas", "portfolio"],
    unit_codes: ["SIT103", "SIT191"],
    topic: "careers",
    helpful_count: 112,
    hours_ago: 2,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "f3",
    author_id: "p5",
    lang: "en",
    text: "IT students who want a web development internship: here is the portfolio plan I give every mentee, step by step. Week 1 to 3: finish the MDN Learn web development modules on HTML and CSS. Do not skip the accessibility sections, interviewers ask about semantic HTML more than you would think. Week 4 to 6: rebuild one real website you use every day, pixel for pixel, with plain HTML and CSS. No frameworks yet. You will learn more about layout from copying a real page than from ten tutorials. Week 7 to 9: add JavaScript. Make one thing interactive that actually solves a problem for you, like a timetable planner for your Deakin units or a budget tracker. Week 10 onwards: learn React by rebuilding that same project. Now you have a before and after story, which is exactly what interviewers want to hear. Put everything on GitHub with a short README and screenshots, deploy it for free, and link it at the top of your resume. When I hired for my team, a deployed project with a clear README beat a 7-page resume every single time. Use SIT120 as your excuse to polish one of these projects, since the unit literally rewards it.",
    tldr: "A 10-week plan for a web dev internship portfolio: MDN basics with accessibility, clone a real site in plain HTML and CSS, add JavaScript to solve your own problem, then rebuild it in React and deploy it with a clear README.",
    summary_en: null,
    image_url: "https://picsum.photos/id/180/1200/675",
    link_preview: {
      url: "https://developer.mozilla.org/en-US/docs/Learn",
      title: "Learn web development | MDN",
      site: "developer.mozilla.org",
      description: "Free, structured guides to HTML, CSS, JavaScript and accessibility from Mozilla.",
      image: null,
    },
    tags: ["web-development", "internship", "portfolio", "html", "javascript"],
    unit_codes: ["SIT120"],
    topic: "careers",
    helpful_count: 107,
    hours_ago: 1.5,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "f4",
    author_id: "p9",
    lang: "en",
    text: "Honest first year check-in for any CS mentors reading: SIT102 is harder than I expected and I would love advice. Coming from Python in high school, switching to C++ with SplashKit in trimester 1 threw me. The syntax is fine now, but I still freeze on the credit and distinction tasks because I do not know how to break a problem into functions and data structures. For example, the pong game task: I got the paddle moving, but the moment I added scoring and two players my main loop turned into 200 lines of if statements. I have been rewriting it from scratch three times instead of refactoring. I also want to start preparing for internships early and people keep saying algorithms and interviews, but I do not know whether that means LeetCode now or after SIT232. My plan right now is: finish the SplashKit tutorials again, watch a data structures series on YouTube, and try two easy LeetCode problems a week in Python. Is that a sensible plan for a first year, or am I spreading myself too thin? Any tips on structuring game code like pong would be amazing too.",
    tldr: "A first year CS student struggles to structure SIT102 SplashKit code (pong became one giant loop) and asks mentors whether starting data structures and easy LeetCode in Python now is sensible or too much.",
    summary_en: null,
    image_url: "https://picsum.photos/id/48/1200/675",
    link_preview: {
      url: "https://splashkit.io/",
      title: "SplashKit",
      site: "splashkit.io",
      description: "The beginner-friendly game and graphics SDK used in SIT102, with tutorials and guides.",
      image: null,
    },
    tags: ["python", "algorithms", "data-structures", "interviews", "beginners"],
    unit_codes: ["SIT102"],
    topic: "study-tips",
    helpful_count: 64,
    hours_ago: 0.5,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "f5",
    author_id: "p8",
    lang: "en",
    text: "MMK101 group presentation next week and I would really appreciate feedback from any marketing seniors. Our brief is to relaunch a local cafe brand for university students. We ran a small survey in our tutorial and found that students care more about study-friendly space and power outlets than about price, which surprised us. So our idea is to position the cafe as a study spot, not a cheap coffee place. For the 4Ps: product is a study bundle with coffee and a pastry, price stays mid-range, place is the existing store with extra outlets and quiet hours, and promotion is Instagram and TikTok content filmed during exam weeks. I made the slides in Canva using a brand board like the one in the photo. My worries: is a survey of 30 classmates enough evidence of consumer behaviour, or will the marker say it is biased? And how do we present the promotion plan without it sounding like a list of social media apps? I also want to practise presenting slowly and clearly because English is my second language. Any advice on structure or on the HubSpot course modules worth doing before Friday would help a lot.",
    tldr: "An MMK101 team repositions a local cafe as a student study spot based on a 30-person survey, and asks seniors whether that evidence is strong enough and how to present the promotion plan and deliver the talk clearly.",
    summary_en: null,
    image_url: "https://picsum.photos/id/20/1200/675",
    link_preview: {
      url: "https://academy.hubspot.com/",
      title: "HubSpot Academy",
      site: "academy.hubspot.com",
      description: "Free marketing courses on content, social media and inbound strategy, with certificates.",
      image: null,
    },
    tags: ["marketing", "consumer-behaviour", "presentations", "canva", "assignments"],
    unit_codes: ["MMK101"],
    topic: "unit-review",
    helpful_count: 58,
    hours_ago: 0.8,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Sarah Chen (p1, CS mentor at Google) ----
  {
    id: "s1",
    author_id: "p1",
    lang: "en",
    text: "The single highest-leverage thing I did at uni: solving 2 LeetCode easies a week from year 1. Not grinding, just consistency. By the time Google interviews came around in final year, mediums felt routine. Start slow, stay regular.",
    tldr: null,
    summary_en: null,
    tags: ["interviews", "algorithms", "consistency"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 124,
    hours_ago: 5,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s2",
    author_id: "p1",
    lang: "en",
    text: "SIT232 review since people keep asking: it's the most important unit in the CS degree. Object oriented design is what every internship interviewer probed me on. The custom program assignment is your chance to build something real. I built a tiny game engine and talked about it in every interview for two years. Do NOT copy the task sheet example. Pick something you actually care about, scope it small, and iterate. The design patterns lectures feel abstract in week 6 but they are the vocabulary of every code review you'll ever sit in. Attend the labs; the tutors basically hand you the assignment structure.",
    tldr: "SIT232 is the most career-relevant CS unit. Build a custom project you care about. It becomes interview material for years.",
    summary_en: null,
    tags: ["unit-review", "oop", "interviews"],
    unit_codes: ["SIT232"],
    topic: "unit-review",
    helpful_count: 98,
    hours_ago: 26,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s3",
    author_id: "p1",
    lang: "en",
    text: "Google interview prep that actually mattered: 1) NeetCode 150, not random problems. 2) Mock interviews with a friend, out loud, on a whiteboard. 3) One system design primer read twice. Everything else was noise. https://neetcode.io/practice",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://neetcode.io/practice",
      title: "NeetCode 150: curated coding interview problems",
      site: "neetcode.io",
      description:
        "A structured list of 150 problems grouped by pattern, with free video explanations for each one.",
      image: "/demo/link-neetcode.svg",
    },
    tags: ["interviews", "algorithms", "internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 156,
    hours_ago: 72,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s4",
    author_id: "p1",
    lang: "en",
    text: "Unpopular opinion: your GPA matters less than one finished side project. I got the Google internship with a 74 average and a half-decent distributed key-value store on GitHub. Recruiters can't run your transcript.",
    tldr: null,
    summary_en: null,
    tags: ["projects", "internship", "portfolio"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 87,
    hours_ago: 120,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s5",
    author_id: "p1",
    lang: "en",
    text: "For first years asking where to start with Python beyond SIT102: build a CLI tool you'll actually use. Mine was a script that renamed my lecture downloads. Ugly code, real problem, learned more than any tutorial.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/code.svg",
    tags: ["python", "projects", "beginners"],
    unit_codes: ["SIT102"],
    topic: "study-tips",
    helpful_count: 64,
    hours_ago: 160,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Duc Tran (p2, CS Y3 mentor, tutor) ----
  {
    id: "d1",
    author_id: "p2",
    lang: "en",
    text: "As a SIT102 tutor: the students who pass comfortably are the ones who type out every lecture example themselves instead of just reading it. Muscle memory is real for syntax. 20 minutes a day beats a 6-hour panic session.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "beginners", "programming"],
    unit_codes: ["SIT102"],
    topic: "study-tips",
    helpful_count: 73,
    hours_ago: 8,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d2",
    author_id: "p2",
    lang: "en",
    text: "How I got the Atlassian internship as a year 3 with no prior experience: I tutored. Teaching data structures to first years forced me to actually understand them, and 'casual academic tutor' on a resume starts conversations. Apply to tutor the moment you finish a unit with a D or HD. The bar is lower than you think and the pay beats retail. Then in interviews, every 'explain X to me' question is literally your day job. Three of the five Atlassian behavioural questions I answered with tutoring stories.",
    tldr: "Tutoring a unit you did well in is an underrated internship strategy: it deepens your understanding, pays well, and gives you interview stories.",
    summary_en: null,
    tags: ["internship", "tutoring", "interviews"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 91,
    hours_ago: 30,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d3",
    author_id: "p2",
    lang: "en",
    text: "Java tip for OOP students: stop fighting the compiler and start reading the error messages top to bottom. 90% of the questions I get in labs are answered in the first line of the stack trace.",
    tldr: null,
    summary_en: null,
    tags: ["java", "oop", "study-tips"],
    unit_codes: ["SIT232"],
    topic: "study-tips",
    helpful_count: 45,
    hours_ago: 50,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d4",
    author_id: "p2",
    lang: "en",
    text: "Reminder for year 1s: the maths units feel disconnected from programming until SIT215. Then suddenly graph theory is pathfinding and probability is machine learning. Keep your notes.",
    tldr: null,
    summary_en: null,
    tags: ["maths", "study-tips"],
    unit_codes: ["SIT215"],
    topic: "study-tips",
    helpful_count: 38,
    hours_ago: 96,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Priya Sharma (p3, DS mentor at Canva) ----
  {
    id: "pr1",
    author_id: "p3",
    lang: "en",
    text: "The Canva analyst interview was 70% SQL. Not fancy SQL, just clean joins, window functions, and explaining your reasoning out loud. Mode's free SQL tutorial covers all of it. SIT191 theory came up exactly once. https://mode.com/sql-tutorial",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://mode.com/sql-tutorial",
      title: "The SQL Tutorial for Data Analysis",
      site: "mode.com",
      description:
        "Free interactive SQL lessons from basic queries through window functions, run against real datasets.",
      image: null,
    },
    tags: ["sql", "interviews", "analyst-internship"],
    unit_codes: ["SIT191"],
    topic: "careers",
    helpful_count: 82,
    hours_ago: 12,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr2",
    author_id: "p3",
    lang: "en",
    text: "Kaggle advice for students: don't chase leaderboard positions. Pick one finished competition, write up your approach as a blog post, and put THAT on your resume. A documented 60th percentile beats an unexplained bronze.",
    tldr: null,
    summary_en: null,
    tags: ["kaggle", "portfolio", "analyst-internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 67,
    hours_ago: 40,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr3",
    author_id: "p3",
    lang: "en",
    text: "Honest SIT191 review: the content is dry but it is load-bearing for the whole degree. What saved me was redoing every workshop exercise in Python with pandas afterwards. Twice the work in year 1, half the work every year after, because every later unit assumes you can wrangle a dataframe. StatQuest on YouTube explains the theory better than the lectures, so watch the video BEFORE the lecture and the lecture becomes revision. The exam is formula-sheet friendly; make your own sheet, don't download one.",
    tldr: "SIT191 is dry but foundational. Redo the workshop exercises in pandas, watch StatQuest before lectures, and build your own formula sheet.",
    summary_en: null,
    tags: ["unit-review", "statistics", "pandas"],
    unit_codes: ["SIT191"],
    topic: "unit-review",
    helpful_count: 54,
    hours_ago: 80,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr4",
    author_id: "p3",
    lang: "en",
    text: "Tableau Public is free and recruiters actually click the links. Two polished dashboards on real datasets (not iris, not titanic) did more for my applications than my entire academic transcript. Here's the one that got the most questions in interviews.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/dashboard.svg",
    tags: ["tableau", "portfolio", "analyst-internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 49,
    hours_ago: 130,
    flag_reason: null,
    is_demo: true,
  },

  // ---- James Wilson (p4, Business Y3 mentor) ----
  {
    id: "j1",
    author_id: "p4",
    lang: "en",
    text: "PwC vacationer application timeline nobody tells you: applications open FEBRUARY for the following summer. Year 2s, set a reminder now. Half my cohort missed it because they assumed winter openings.",
    tldr: null,
    summary_en: null,
    tags: ["consulting", "internship", "deadlines"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 76,
    hours_ago: 15,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j2",
    author_id: "p4",
    lang: "en",
    text: "Case competitions are the business degree cheat code. One state final = three interview stories, two referees, and a line on the resume that every consulting screener stops at. MAA103 group work is the training ground, so treat it seriously.",
    tldr: null,
    summary_en: null,
    tags: ["case-competitions", "consulting", "networking"],
    unit_codes: ["MAA103"],
    topic: "careers",
    helpful_count: 58,
    hours_ago: 45,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j3",
    author_id: "p4",
    lang: "en",
    text: "Excel skills that got me through every business unit and the PwC internship, in order of use: XLOOKUP, pivot tables, conditional formatting, INDEX/MATCH, and knowing when to stop using Excel and ask for the real database.",
    tldr: null,
    summary_en: null,
    tags: ["excel", "study-tips"],
    unit_codes: ["MIS171"],
    topic: "study-tips",
    helpful_count: 41,
    hours_ago: 90,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j4",
    author_id: "p4",
    lang: "en",
    text: "Networking event survival guide for introverts: arrive early when it's quiet, ask people what they're working on (never 'what do you do'), and leave after 3 real conversations. Quality over laps of the room.",
    tldr: null,
    summary_en: null,
    tags: ["networking", "wellbeing"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 63,
    hours_ago: 140,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Linh Nguyen (p5, IT mentor, frontend dev, posts in Vietnamese too) ----
  {
    id: "l1",
    author_id: "p5",
    lang: "en",
    text: "I used to think I had to learn every framework before anyone would hire me. Completely wrong. I built 3 projects in React, wrote proper READMEs, deployed them to Vercel. Every interview only asked about those 3. Learning one thing deeply beats skimming ten.",
    tldr: null,
    summary_en: null,
    tags: ["react", "portfolio", "projects"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 71,
    hours_ago: 10,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l2",
    author_id: "p5",
    lang: "en",
    text: "SIT120 is secretly a portfolio unit. My final assignment became the centrepiece of my job applications. Pick a real problem, polish the UI, and deploy it. A live URL in a resume gets clicked, a zip file does not.",
    tldr: null,
    summary_en: null,
    tags: ["unit-review", "portfolio", "web-development"],
    unit_codes: ["SIT120"],
    topic: "unit-review",
    helpful_count: 52,
    hours_ago: 35,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l3",
    author_id: "p5",
    lang: "en",
    text: "To first-year IT students, especially international ones: don't let your English stop you from asking questions in labs. The tutors here deal with international students every single day and they do not care about your accent. I sat silent through an entire trimester because I was embarrassed, and I wasted a lot of tuition doing it. Asking a 'stupid' question beats submitting late.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "international-students", "wellbeing"],
    unit_codes: [],
    topic: "wellbeing",
    helpful_count: 88,
    hours_ago: 60,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l4",
    author_id: "p5",
    lang: "en",
    text: "The Odin Project plus one deployed personal site taught me more practical web dev than any single unit. Uni gives you the theory and the paper; you have to give yourself the reps. Both matter. https://www.theodinproject.com",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://www.theodinproject.com",
      title: "The Odin Project: free full stack curriculum",
      site: "theodinproject.com",
      description:
        "Project-based path through HTML, CSS, JavaScript and deployment. You build everything yourself.",
      image: "/demo/link-odin.svg",
    },
    tags: ["web-development", "resources", "javascript"],
    unit_codes: [],
    topic: "resources",
    helpful_count: 47,
    hours_ago: 100,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l5",
    author_id: "p5",
    lang: "en",
    text: "My job hunt numbers, for anyone who needs them: 47 applications, 5 interviews, 1 offer. I wanted to quit roughly once a month. The thing that actually changed my results was asking for feedback after every rejection. Only about 1 in 10 companies replied, but those replies told me my CV buried my projects on page 2 and that I was explaining what I built instead of why it was hard. Don't apply into silence. Treat each rejection as data, fix one thing, send the next one. And put your projects on the internet where a recruiter can click them, not in a folder on your laptop.",
    tldr: "47 applications, 5 interviews, 1 offer. Asking for feedback after each rejection (even though few replied) was the turning point.",
    summary_en: null,
    tags: ["job-hunt", "portfolio", "wellbeing"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 103,
    hours_ago: 170,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Ahmed Hassan (p6, Design Y3 mentor) ----
  {
    id: "a1",
    author_id: "p6",
    lang: "en",
    text: "REA internship folio review: they spent 15 minutes on ONE case study and skipped the rest. Depth of process beats volume of shots. Show the messy middle: research, dead ends, iterations, not just the final screens.",
    tldr: null,
    summary_en: null,
    tags: ["portfolio", "ux-research", "internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 44,
    hours_ago: 20,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "a2",
    author_id: "p6",
    lang: "en",
    text: "ADD105 tip: photograph your sketches and sticky-note walls from day one. The folio deadline in week 12 is really a documentation test, and you cannot recreate process photos you never took.",
    tldr: null,
    summary_en: null,
    tags: ["unit-review", "study-tips", "portfolio"],
    unit_codes: ["ADD105"],
    topic: "unit-review",
    helpful_count: 36,
    hours_ago: 55,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "a3",
    author_id: "p6",
    lang: "en",
    text: "Figma tip that levels up student work instantly: auto layout everything, then set up 4 text styles and 6 colour variables before you design a single screen. Constraints make you faster, not slower.",
    tldr: null,
    summary_en: null,
    tags: ["figma", "ui-design", "study-tips"],
    unit_codes: [],
    topic: "study-tips",
    helpful_count: 57,
    hours_ago: 110,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Minh Le (p7, IT Y1 mentee) ----
  {
    id: "m1",
    author_id: "p7",
    lang: "en",
    text: "Week 4 of SIT102 and arrays finally clicked after I drew them as parking spots on paper. Sharing in case it helps another year 1, because sometimes the dumb analogy is the one that works.",
    tldr: null,
    summary_en: null,
    tags: ["beginners", "study-tips", "python"],
    unit_codes: ["SIT102"],
    topic: "study-tips",
    helpful_count: 29,
    hours_ago: 3,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "m2",
    author_id: "p7",
    lang: "en",
    text: "Is it normal to feel behind in first year? Everyone in my lab seems to have been coding since they were 12 and I started 6 weeks ago. Any seniors been through this?",
    tldr: null,
    summary_en: null,
    tags: ["wellbeing", "beginners"],
    unit_codes: [],
    topic: "wellbeing",
    helpful_count: 48,
    hours_ago: 28,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "m3",
    author_id: "p7",
    lang: "en",
    text: "Built my first ever webpage for a uni task and put it on GitHub Pages. It's just HTML and CSS and it's ugly, but it's MINE and it's live on the internet. Small wins.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/webpage.svg",
    tags: ["web-development", "beginners", "projects"],
    unit_codes: ["SIT111"],
    topic: "projects",
    helpful_count: 61,
    hours_ago: 85,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Lan Pham (p8, Business Y2 mentee) ----
  {
    id: "lp1",
    author_id: "p8",
    lang: "en",
    text: "Exchange application diary, entry 1: the hardest part so far is the unit mapping spreadsheet, not the essays. Start matching your units to the host uni's catalogue MONTHS early. Asking past exchange students for their approved mappings saved me weeks.",
    tldr: null,
    summary_en: null,
    tags: ["exchange", "study-tips", "deadlines"],
    unit_codes: [],
    topic: "study-tips",
    helpful_count: 33,
    hours_ago: 18,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "lp2",
    author_id: "p8",
    lang: "en",
    text: "Has anyone in Business actually done an exchange? I'm torn between trimester 1 and trimester 2 of third year. I keep hearing trimester 2 has better scholarship odds, but it clashes with internship recruiting season. Would really appreciate advice from someone who has been through it.",
    tldr: null,
    summary_en: null,
    tags: ["exchange", "consulting", "international-students"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 21,
    hours_ago: 42,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "lp3",
    author_id: "p8",
    lang: "en",
    text: "Presentation hack from my public speaking elective: record yourself once on your phone before any assessed talk. Painful to watch, instantly fixes the filler words. My MAA103 pitch went from a credit to a distinction.",
    tldr: null,
    summary_en: null,
    tags: ["presentations", "study-tips"],
    unit_codes: ["MAA103"],
    topic: "study-tips",
    helpful_count: 27,
    hours_ago: 105,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Tom Baker (p9, CS Y1 mentee) ----
  {
    id: "t1",
    author_id: "p9",
    lang: "en",
    text: "Made Pong in Unity following a YouTube tutorial, then remade it WITHOUT the tutorial. The second time took 3x longer and taught me 10x more. Tutorial hell is real, escape early.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/pong.svg",
    tags: ["game-development", "projects", "beginners"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 39,
    hours_ago: 22,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "t2",
    author_id: "p9",
    lang: "en",
    text: "Anyone know if game dev clubs look at first years? I want to join a jam team but my only finished project is a Pong clone. Do I wait until I'm better or just show up?",
    tldr: null,
    summary_en: null,
    tags: ["game-development", "beginners", "networking"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 18,
    hours_ago: 48,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "t3",
    author_id: "p9",
    lang: "en",
    text: "PSA for SIT102 students: the practice exam on CloudDeakin is from an older curriculum. My tutor said focus on the lab tasks from weeks 8-11 instead. Would've wasted my whole study week on the wrong material.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "exams", "beginners"],
    unit_codes: ["SIT102"],
    topic: "study-tips",
    helpful_count: 55,
    hours_ago: 68,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Aisha Khan (p10, DS Y2 mentee) ----
  {
    id: "ak1",
    author_id: "p10",
    lang: "en",
    text: "First Kaggle competition done! Finished 412th out of 800 which sounds bad until you realise I couldn't write a groupby without googling it 3 months ago. Writing up my approach this weekend like the seniors suggested.",
    tldr: null,
    summary_en: null,
    tags: ["kaggle", "pandas", "projects"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 42,
    hours_ago: 14,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "ak2",
    author_id: "p10",
    lang: "en",
    text: "SQL study group for SIT103, Thursdays 4pm in the library. We're 4 people working through the Mode tutorial together. Two spots left, reply if keen. Beginners welcome, that's the point.",
    tldr: null,
    summary_en: null,
    tags: ["sql", "study-tips", "networking"],
    unit_codes: ["SIT103"],
    topic: "study-tips",
    helpful_count: 25,
    hours_ago: 38,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "ak3",
    author_id: "p10",
    lang: "en",
    text: "Text me on 0412 345 678 if you want my SIT191 notes, selling the full trimester bundle for $50. Also have last year's assignment solutions.",
    tldr: null,
    summary_en: null,
    tags: ["statistics", "notes"],
    unit_codes: ["SIT191"],
    topic: "resources",
    helpful_count: 2,
    hours_ago: 58,
    flag_reason: "Contains personal contact info and offers assignment solutions for sale. Needs human review.",
    is_demo: true,
  },

  // ---- Chris Park (p11, IT Y2 mentee) ----
  {
    id: "c1",
    author_id: "p11",
    lang: "en",
    text: "Passed the CompTIA Security+ while doing SIT202. The unit content overlaps about 40% so studying for both at once was efficient. Happy to share my study plan mapping unit weeks to exam objectives.",
    tldr: null,
    summary_en: null,
    tags: ["cybersecurity", "certifications", "study-tips"],
    unit_codes: ["SIT202"],
    topic: "study-tips",
    helpful_count: 34,
    hours_ago: 32,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "c2",
    author_id: "p11",
    lang: "en",
    text: "Got the exact final exam questions for SIT202 from someone who sat it last trimester, DM me and I'll send them through before Friday.",
    tldr: null,
    summary_en: null,
    tags: ["exams", "networking"],
    unit_codes: ["SIT202"],
    topic: "study-tips",
    helpful_count: 1,
    hours_ago: 44,
    flag_reason: "Possible sharing of exam questions. Academic integrity concern, needs human review.",
    is_demo: true,
  },

  // ---- Emma Davis (p12, Design Y1 mentee) ----
  {
    id: "e1",
    author_id: "p12",
    lang: "en",
    text: "Redesigned my student club's event poster in Figma using the auto layout tips from a senior here. First time something I made got printed! Posting the before/after to my baby portfolio.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/poster.svg",
    tags: ["figma", "portfolio", "ui-design"],
    unit_codes: ["ADD105"],
    topic: "projects",
    helpful_count: 31,
    hours_ago: 6,
    flag_reason: null,
    is_demo: true,
  },
  // ---- Marketing (MMK101) ----
  {
    id: "hv1",
    author_id: "p13",
    lang: "en",
    text: "MMK101 tip for anyone who finds the theory dry: every time a lecture introduces a framework, pick one brand you actually buy from and apply it on the spot. I did the 4Ps on my favourite bubble tea shop and suddenly segmentation, pricing and positioning were not abstract anymore. The exam questions are basically this exercise with a brand they choose.",
    tldr: "Apply every MMK101 framework to a brand you already know. The exam is the same exercise with their brand.",
    summary_en: null,
    tags: ["marketing", "study-tips", "exams"],
    unit_codes: ["MMK101"],
    topic: "study-tips",
    helpful_count: 58,
    hours_ago: 14,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "hv2",
    author_id: "p13",
    lang: "en",
    text: "To the first years who messaged me stressed about the MMK101 case study: you do not need to sound like a textbook. Clear structure beats fancy words. Situation, problem, two options, your recommendation, why. That's it.",
    tldr: null,
    summary_en: null,
    tags: ["marketing", "assignments", "writing"],
    unit_codes: ["MMK101"],
    topic: "unit-review",
    helpful_count: 41,
    hours_ago: 60,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "rm1",
    author_id: "p14",
    lang: "en",
    text: "Hot take: MMK101 is the most useful first-year business unit if you want an agency job. I used my case study on a local gym's Instagram as a portfolio piece and it got me my part-time social media role. Treat assignments like client work.",
    tldr: null,
    summary_en: null,
    tags: ["marketing", "portfolio", "internship"],
    unit_codes: ["MMK101"],
    topic: "careers",
    helpful_count: 37,
    hours_ago: 30,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "lp4",
    author_id: "p8",
    lang: "en",
    text: "Starting MMK101 this trimester and honestly the readings are a lot. Is there a senior who explains things slowly? I understand better with real examples than slides.",
    tldr: null,
    summary_en: null,
    tags: ["marketing", "beginners"],
    unit_codes: ["MMK101"],
    topic: "study-tips",
    helpful_count: 9,
    hours_ago: 3,
    flag_reason: null,
    is_demo: true,
  },
];

const MEDIA_POOL = [
  { image_url: "/demo/code.svg" },
  { image_url: "/demo/dashboard.svg" },
  { image_url: "/demo/webpage.svg" },
  { image_url: "/demo/pong.svg" },
  { image_url: "/demo/poster.svg" },
  {
    link_preview: {
      url: "https://www.deakin.edu.au/students",
      title: "Deakin Students",
      site: "deakin.edu.au",
      description: "Official student hub for units, support and key dates.",
      image: "/demo/webpage.svg",
    },
  },
  {
    link_preview: {
      url: "https://www.theodinproject.com/",
      title: "The Odin Project",
      site: "theodinproject.com",
      description: "Free full-stack curriculum used by a lot of our IT mentors.",
      image: "/demo/link-odin.svg",
    },
  },
  {
    link_preview: {
      url: "https://neetcode.io/practice",
      title: "NeetCode 150",
      site: "neetcode.io",
      description: "Curated interview problems with free video explanations.",
      image: "/demo/link-neetcode.svg",
    },
  },
];

function withDemoMedia(posts) {
  return posts.map((p, i) =>
    p.image_url || p.link_preview ? p : { ...p, ...MEDIA_POOL[i % MEDIA_POOL.length] }
  );
}

export const POSTS = withDemoMedia(RAW_POSTS);

// Demo replies so unit discussions look alive before anyone types.
export const REPLIES = [
  { id: "r1", post_id: "s2", author_id: "p7", text: "Doing the custom project early saved me too. I started week 3 and still barely finished.", hours_ago: 40 },
  { id: "r2", post_id: "s2", author_id: "p12", text: "Any tips for picking a project scope that isn't too ambitious?", hours_ago: 32 },
  { id: "r3", post_id: "s5", author_id: "p9", text: "Doing every lab twice sounds like a grind but it genuinely works. The exam felt familiar.", hours_ago: 100 },
  { id: "r4", post_id: "d1", author_id: "p10", text: "Wish I had read this in week 1. The recursion week filtered half my friends.", hours_ago: 55 },
  { id: "r5", post_id: "pr1", author_id: "p8", text: "The weekly quizzes carried my grade. Do them the day the content drops.", hours_ago: 70 },
  { id: "r6", post_id: "m1", author_id: "p1", text: "Great writeup. Also: the lab solutions from week 6 onwards reuse earlier patterns, so revising old labs pays twice.", hours_ago: 20 },
  { id: "r7", post_id: "j2", author_id: "p11", text: "How maths-heavy is it really? I keep hearing different things.", hours_ago: 90 },
  { id: "r8", post_id: "j2", author_id: "p4", text: "More logic than maths. If you can follow a budget spreadsheet you can pass.", hours_ago: 85 },
  { id: "r9", post_id: "c1", author_id: "p5", text: "The packet tracer labs are the whole unit. Do not skip them.", hours_ago: 30 },
  { id: "r10", post_id: "a2", author_id: "p6", text: "Auto layout changed my life, glad the tip landed!", hours_ago: 44 },
  { id: "r11", post_id: "lp4", author_id: "p13", text: "Hi Lan! Totally normal, the readings are heavy in weeks 1-3. Try applying each chapter to a brand you like. Happy to help if you get stuck.", hours_ago: 2 },
  { id: "r12", post_id: "hv1", author_id: "p8", text: "This is exactly what I needed. Doing the 4Ps on Highlands Coffee tonight.", hours_ago: 2 },
];

export function getProfile(id) {
  return PROFILES.find((p) => p.id === id) ?? null;
}

export function getPostsByAuthor(authorId) {
  return POSTS.filter((p) => p.author_id === authorId);
}

export function getSeedReplies(postId) {
  return REPLIES.filter((r) => r.post_id === postId);
}
