// Labelled demo data. In Feature 2+ this shape moves to Supabase tables
// (profiles, posts). Keep field names snake_case to match the future schema.
//
// Optional post fields, omitted when unused:
//   image_url     string, attached image (local /demo/* here, Cloudinary URL when live)
//   link_preview  { url, title, site, description, image|null }
// Seed text is English-only. `lang` + `summary_en` stay in the schema because
// live posts in other languages still get an AI English summary.

export const PROFILES = [
  // ---- Mentors / seniors ----
  {
    id: "p1",
    name: "Sarah Chen",
    handle: "sarahc",
    role: "mentor",
    course: "CS",
    year: null, // graduated
    verified: true,
    skills: ["python", "algorithms", "interviews", "distributed-systems"],
    goals: [],
    outcome: "Software Engineer at Google (graduated 2024)",
    units: [
      { code: "COS10009", name: "Introduction to Programming", tip: "Do every lab twice. The exam is the labs in disguise." },
      { code: "COS20007", name: "Object Oriented Programming", tip: "Build the custom project early, don't leave it to week 11." },
      { code: "COS30019", name: "Intro to AI", tip: "The search assignment is 80% of the learning. Start week 1." },
    ],
    resources: [
      { label: "NeetCode 150 (YouTube)", url: "https://www.youtube.com/@NeetCode", type: "YouTube" },
      { label: "Grokking Algorithms", url: "https://www.manning.com/books/grokking-algorithms", type: "Book" },
    ],
    is_demo: true,
  },
  {
    id: "p2",
    name: "Duc Tran",
    handle: "ductran",
    role: "mentor",
    course: "CS",
    year: 3,
    verified: true,
    skills: ["java", "data-structures", "tutoring", "interviews"],
    goals: [],
    outcome: "Tutor at Swinburne, incoming intern at Atlassian",
    units: [
      { code: "COS10009", name: "Introduction to Programming", tip: "Pascal first semester surprises people. Trust the process." },
      { code: "COS20007", name: "Object Oriented Programming", tip: "Learn the design patterns lectures properly, they come back in year 3." },
    ],
    resources: [
      { label: "Java MOOC (University of Helsinki)", url: "https://java-programming.mooc.fi/", type: "Course" },
    ],
    is_demo: true,
  },
  {
    id: "p3",
    name: "Priya Sharma",
    handle: "priyash",
    role: "mentor",
    course: "Data Science",
    year: null,
    verified: true,
    skills: ["sql", "pandas", "statistics", "tableau"],
    goals: [],
    outcome: "Data Analyst at Canva (graduated 2025)",
    units: [
      { code: "STA10003", name: "Foundations of Statistics", tip: "SPSS is clunky, redo everything in Python after and it clicks." },
      { code: "COS20015", name: "Fundamentals of Data Management", tip: "SQL joins on paper before touching the keyboard." },
    ],
    resources: [
      { label: "Mode SQL Tutorial", url: "https://mode.com/sql-tutorial", type: "Website" },
      { label: "StatQuest (YouTube)", url: "https://www.youtube.com/@statquest", type: "YouTube" },
    ],
    is_demo: true,
  },
  {
    id: "p4",
    name: "James Wilson",
    handle: "jamesw",
    role: "mentor",
    course: "Business",
    year: 3,
    verified: true,
    skills: ["accounting", "excel", "case-competitions", "networking"],
    goals: [],
    outcome: "PwC summer vacationer 2026",
    units: [
      { code: "ACC10007", name: "Financial Information for Decision Making", tip: "The group assignment carries the unit. Pick your team fast." },
      { code: "INF10024", name: "Business Analytics in Practice", tip: "Learn pivot tables before the first workshop." },
    ],
    resources: [
      { label: "Corporate Finance Institute free courses", url: "https://corporatefinanceinstitute.com/", type: "Course" },
    ],
    is_demo: true,
  },
  {
    id: "p5",
    name: "Linh Nguyen",
    handle: "linhng",
    role: "mentor",
    course: "IT",
    year: null,
    verified: true,
    skills: ["javascript", "react", "css", "portfolio"],
    goals: [],
    outcome: "Frontend Developer at a Melbourne startup (graduated 2025)",
    units: [
      { code: "COS10026", name: "Computing Technology Inquiry Project", tip: "Your first real website. Make it something you'd show an employer." },
      { code: "COS30043", name: "Interface Design and Development", tip: "This unit IS your portfolio if you take it seriously." },
    ],
    resources: [
      { label: "The Odin Project", url: "https://www.theodinproject.com/", type: "Website" },
      { label: "Josh Comeau CSS course", url: "https://www.joshwcomeau.com/", type: "Website" },
    ],
    is_demo: true,
  },
  {
    id: "p6",
    name: "Ahmed Hassan",
    handle: "ahmedh",
    role: "mentor",
    course: "Design",
    year: 3,
    verified: true,
    skills: ["figma", "ux-research", "portfolio", "prototyping"],
    goals: [],
    outcome: "UX intern at REA Group",
    units: [
      { code: "DDD10001", name: "Design Thinking", tip: "Document your process obsessively. The folio is the grade." },
      { code: "DIG30004", name: "UX Strategy", tip: "Interview real users, not your friends pretending to be users." },
    ],
    resources: [
      { label: "Figma Learn", url: "https://www.figma.com/resource-library/", type: "Website" },
      { label: "NNGroup articles", url: "https://www.nngroup.com/articles/", type: "Website" },
    ],
    is_demo: true,
  },
  // ---- Mentees / current students ----
  {
    id: "p7",
    name: "Minh Le",
    handle: "minhle",
    role: "mentee",
    course: "IT",
    year: 1,
    verified: true,
    skills: ["html", "python"],
    goals: ["internship", "web-development"],
    outcome: null,
    units: [
      { code: "COS10009", name: "Introduction to Programming", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p8",
    name: "Lan Pham",
    handle: "lanpham",
    role: "mentee",
    course: "Business",
    year: 2,
    verified: false,
    skills: ["excel", "presentations"],
    goals: ["exchange", "consulting"],
    outcome: null,
    units: [
      { code: "ACC10007", name: "Financial Information for Decision Making", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p9",
    name: "Tom Baker",
    handle: "tombaker",
    role: "mentee",
    course: "CS",
    year: 1,
    verified: true,
    skills: ["python", "unity"],
    goals: ["game-development", "internship"],
    outcome: null,
    units: [
      { code: "COS10009", name: "Introduction to Programming", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p10",
    name: "Aisha Khan",
    handle: "aishak",
    role: "mentee",
    course: "Data Science",
    year: 2,
    verified: true,
    skills: ["python", "sql", "pandas"],
    goals: ["kaggle", "analyst-internship"],
    outcome: null,
    units: [
      { code: "STA10003", name: "Foundations of Statistics", tip: null },
      { code: "COS20015", name: "Fundamentals of Data Management", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p11",
    name: "Chris Park",
    handle: "chrisp",
    role: "mentee",
    course: "IT",
    year: 2,
    verified: false,
    skills: ["networking", "linux"],
    goals: ["cybersecurity", "certifications"],
    outcome: null,
    units: [
      { code: "TNE10006", name: "Networks and Switching", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
  {
    id: "p12",
    name: "Emma Davis",
    handle: "emmad",
    role: "mentee",
    course: "Design",
    year: 1,
    verified: true,
    skills: ["figma"],
    goals: ["portfolio", "ui-design"],
    outcome: null,
    units: [
      { code: "DDD10001", name: "Design Thinking", tip: null },
    ],
    resources: [],
    is_demo: true,
  },
];

// Personas available in the demo switcher (subset of profiles).
export const PERSONA_IDS = ["p7", "p10", "p8", "p2", "p1"];

export const POSTS = [
  // ---- Sarah Chen (p1, CS mentor at Google) ----
  {
    id: "s1",
    author_id: "p1",
    lang: "en",
    text: "The single highest-leverage thing I did at uni: solving 2 LeetCode easies a week from year 1. Not grinding, just consistency. By the time Google interviews came around in final year, mediums felt routine. Start slow, stay regular.",
    tldr: null,
    summary_en: null,
    tags: ["interviews", "algorithms", "consistency"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 124,
    hours_ago: 5,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s2",
    author_id: "p1",
    lang: "en",
    text: "COS20007 review since people keep asking: it's the most important unit in the CS degree. Object oriented design is what every internship interviewer probed me on. The custom program assignment is your chance to build something real. I built a tiny game engine and talked about it in every interview for two years. Do NOT copy the task sheet example. Pick something you actually care about, scope it small, and iterate. The design patterns lectures feel abstract in week 6 but they are the vocabulary of every code review you'll ever sit in. Attend the labs; the tutors basically hand you the assignment structure.",
    tldr: "COS20007 is the most career-relevant CS unit. Build a custom project you care about. It becomes interview material for years.",
    summary_en: null,
    tags: ["unit-review", "oop", "interviews"],
    unit_codes: ["COS20007"],
    topic: "unit-review",
    helpful_count: 98,
    hours_ago: 26,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s3",
    author_id: "p1",
    lang: "en",
    text: "Google interview prep that actually mattered: 1) NeetCode 150, not random problems. 2) Mock interviews with a friend, out loud, on a whiteboard. 3) One system design primer read twice. Everything else was noise. https://neetcode.io/practice",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://neetcode.io/practice",
      title: "NeetCode 150: curated coding interview problems",
      site: "neetcode.io",
      description:
        "A structured list of 150 problems grouped by pattern, with free video explanations for each one.",
      image: "/demo/link-neetcode.svg",
    },
    tags: ["interviews", "algorithms", "internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 156,
    hours_ago: 72,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s4",
    author_id: "p1",
    lang: "en",
    text: "Unpopular opinion: your GPA matters less than one finished side project. I got the Google internship with a 74 average and a half-decent distributed key-value store on GitHub. Recruiters can't run your transcript.",
    tldr: null,
    summary_en: null,
    tags: ["projects", "internship", "portfolio"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 87,
    hours_ago: 120,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "s5",
    author_id: "p1",
    lang: "en",
    text: "For first years asking where to start with Python beyond COS10009: build a CLI tool you'll actually use. Mine was a script that renamed my lecture downloads. Ugly code, real problem, learned more than any tutorial.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/code.svg",
    tags: ["python", "projects", "beginners"],
    unit_codes: ["COS10009"],
    topic: "study-tips",
    helpful_count: 64,
    hours_ago: 160,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Duc Tran (p2, CS Y3 mentor, tutor) ----
  {
    id: "d1",
    author_id: "p2",
    lang: "en",
    text: "As a COS10009 tutor: the students who pass comfortably are the ones who type out every lecture example themselves instead of just reading it. Muscle memory is real for syntax. 20 minutes a day beats a 6-hour panic session.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "beginners", "programming"],
    unit_codes: ["COS10009"],
    topic: "study-tips",
    helpful_count: 73,
    hours_ago: 8,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d2",
    author_id: "p2",
    lang: "en",
    text: "How I got the Atlassian internship as a year 3 with no prior experience: I tutored. Teaching data structures to first years forced me to actually understand them, and 'casual academic tutor' on a resume starts conversations. Apply to tutor the moment you finish a unit with a D or HD. The bar is lower than you think and the pay beats retail. Then in interviews, every 'explain X to me' question is literally your day job. Three of the five Atlassian behavioural questions I answered with tutoring stories.",
    tldr: "Tutoring a unit you did well in is an underrated internship strategy: it deepens your understanding, pays well, and gives you interview stories.",
    summary_en: null,
    tags: ["internship", "tutoring", "interviews"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 91,
    hours_ago: 30,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d3",
    author_id: "p2",
    lang: "en",
    text: "Java tip for OOP students: stop fighting the compiler and start reading the error messages top to bottom. 90% of the questions I get in labs are answered in the first line of the stack trace.",
    tldr: null,
    summary_en: null,
    tags: ["java", "oop", "study-tips"],
    unit_codes: ["COS20007"],
    topic: "study-tips",
    helpful_count: 45,
    hours_ago: 50,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "d4",
    author_id: "p2",
    lang: "en",
    text: "Reminder for year 1s: the maths units feel disconnected from programming until COS30019. Then suddenly graph theory is pathfinding and probability is machine learning. Keep your notes.",
    tldr: null,
    summary_en: null,
    tags: ["maths", "study-tips"],
    unit_codes: ["COS30019"],
    topic: "study-tips",
    helpful_count: 38,
    hours_ago: 96,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Priya Sharma (p3, DS mentor at Canva) ----
  {
    id: "pr1",
    author_id: "p3",
    lang: "en",
    text: "The Canva analyst interview was 70% SQL. Not fancy SQL, just clean joins, window functions, and explaining your reasoning out loud. Mode's free SQL tutorial covers all of it. STA10003 theory came up exactly once. https://mode.com/sql-tutorial",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://mode.com/sql-tutorial",
      title: "The SQL Tutorial for Data Analysis",
      site: "mode.com",
      description:
        "Free interactive SQL lessons from basic queries through window functions, run against real datasets.",
      image: null,
    },
    tags: ["sql", "interviews", "analyst-internship"],
    unit_codes: ["STA10003"],
    topic: "careers",
    helpful_count: 82,
    hours_ago: 12,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr2",
    author_id: "p3",
    lang: "en",
    text: "Kaggle advice for students: don't chase leaderboard positions. Pick one finished competition, write up your approach as a blog post, and put THAT on your resume. A documented 60th percentile beats an unexplained bronze.",
    tldr: null,
    summary_en: null,
    tags: ["kaggle", "portfolio", "analyst-internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 67,
    hours_ago: 40,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr3",
    author_id: "p3",
    lang: "en",
    text: "Honest STA10003 review: the content is dry but it is load-bearing for the whole degree. What saved me was redoing every SPSS exercise in Python with pandas after the workshop. Twice the work in year 1, half the work every year after, because every later unit assumes you can wrangle a dataframe. StatQuest on YouTube explains the theory better than the lectures, so watch the video BEFORE the lecture and the lecture becomes revision. The exam is formula-sheet friendly; make your own sheet, don't download one.",
    tldr: "STA10003 is dry but foundational. Redo the SPSS work in pandas, watch StatQuest before lectures, and build your own formula sheet.",
    summary_en: null,
    tags: ["unit-review", "statistics", "pandas"],
    unit_codes: ["STA10003"],
    topic: "unit-review",
    helpful_count: 54,
    hours_ago: 80,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "pr4",
    author_id: "p3",
    lang: "en",
    text: "Tableau Public is free and recruiters actually click the links. Two polished dashboards on real datasets (not iris, not titanic) did more for my applications than my entire academic transcript. Here's the one that got the most questions in interviews.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/dashboard.svg",
    tags: ["tableau", "portfolio", "analyst-internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 49,
    hours_ago: 130,
    flag_reason: null,
    is_demo: true,
  },

  // ---- James Wilson (p4, Business Y3 mentor) ----
  {
    id: "j1",
    author_id: "p4",
    lang: "en",
    text: "PwC vacationer application timeline nobody tells you: applications open FEBRUARY for the following summer. Year 2s, set a reminder now. Half my cohort missed it because they assumed winter openings.",
    tldr: null,
    summary_en: null,
    tags: ["consulting", "internship", "deadlines"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 76,
    hours_ago: 15,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j2",
    author_id: "p4",
    lang: "en",
    text: "Case competitions are the business degree cheat code. One state final = three interview stories, two referees, and a line on the resume that every consulting screener stops at. ACC10007 group work is the training ground, so treat it seriously.",
    tldr: null,
    summary_en: null,
    tags: ["case-competitions", "consulting", "networking"],
    unit_codes: ["ACC10007"],
    topic: "careers",
    helpful_count: 58,
    hours_ago: 45,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j3",
    author_id: "p4",
    lang: "en",
    text: "Excel skills that got me through every business unit and the PwC internship, in order of use: XLOOKUP, pivot tables, conditional formatting, INDEX/MATCH, and knowing when to stop using Excel and ask for the real database.",
    tldr: null,
    summary_en: null,
    tags: ["excel", "study-tips"],
    unit_codes: ["INF10024"],
    topic: "study-tips",
    helpful_count: 41,
    hours_ago: 90,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "j4",
    author_id: "p4",
    lang: "en",
    text: "Networking event survival guide for introverts: arrive early when it's quiet, ask people what they're working on (never 'what do you do'), and leave after 3 real conversations. Quality over laps of the room.",
    tldr: null,
    summary_en: null,
    tags: ["networking", "wellbeing"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 63,
    hours_ago: 140,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Linh Nguyen (p5, IT mentor, frontend dev, posts in Vietnamese too) ----
  {
    id: "l1",
    author_id: "p5",
    lang: "en",
    text: "I used to think I had to learn every framework before anyone would hire me. Completely wrong. I built 3 projects in React, wrote proper READMEs, deployed them to Vercel. Every interview only asked about those 3. Learning one thing deeply beats skimming ten.",
    tldr: null,
    summary_en: null,
    tags: ["react", "portfolio", "projects"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 71,
    hours_ago: 10,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l2",
    author_id: "p5",
    lang: "en",
    text: "COS30043 is secretly a portfolio unit. My final assignment became the centrepiece of my job applications. Pick a real problem, polish the UI, and deploy it. A live URL in a resume gets clicked, a zip file does not.",
    tldr: null,
    summary_en: null,
    tags: ["unit-review", "portfolio", "web-development"],
    unit_codes: ["COS30043"],
    topic: "unit-review",
    helpful_count: 52,
    hours_ago: 35,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l3",
    author_id: "p5",
    lang: "en",
    text: "To first-year IT students, especially international ones: don't let your English stop you from asking questions in labs. The tutors here deal with international students every single day and they do not care about your accent. I sat silent through an entire semester because I was embarrassed, and I wasted a lot of tuition doing it. Asking a 'stupid' question beats submitting late.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "international-students", "wellbeing"],
    unit_codes: [],
    topic: "wellbeing",
    helpful_count: 88,
    hours_ago: 60,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l4",
    author_id: "p5",
    lang: "en",
    text: "The Odin Project plus one deployed personal site taught me more practical web dev than any single unit. Uni gives you the theory and the paper; you have to give yourself the reps. Both matter. https://www.theodinproject.com",
    tldr: null,
    summary_en: null,
    link_preview: {
      url: "https://www.theodinproject.com",
      title: "The Odin Project: free full stack curriculum",
      site: "theodinproject.com",
      description:
        "Project-based path through HTML, CSS, JavaScript and deployment. You build everything yourself.",
      image: "/demo/link-odin.svg",
    },
    tags: ["web-development", "resources", "javascript"],
    unit_codes: [],
    topic: "resources",
    helpful_count: 47,
    hours_ago: 100,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "l5",
    author_id: "p5",
    lang: "en",
    text: "My job hunt numbers, for anyone who needs them: 47 applications, 5 interviews, 1 offer. I wanted to quit roughly once a month. The thing that actually changed my results was asking for feedback after every rejection. Only about 1 in 10 companies replied, but those replies told me my CV buried my projects on page 2 and that I was explaining what I built instead of why it was hard. Don't apply into silence. Treat each rejection as data, fix one thing, send the next one. And put your projects on the internet where a recruiter can click them, not in a folder on your laptop.",
    tldr: "47 applications, 5 interviews, 1 offer. Asking for feedback after each rejection (even though few replied) was the turning point.",
    summary_en: null,
    tags: ["job-hunt", "portfolio", "wellbeing"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 103,
    hours_ago: 170,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Ahmed Hassan (p6, Design Y3 mentor) ----
  {
    id: "a1",
    author_id: "p6",
    lang: "en",
    text: "REA internship folio review: they spent 15 minutes on ONE case study and skipped the rest. Depth of process beats volume of shots. Show the messy middle: research, dead ends, iterations, not just the final screens.",
    tldr: null,
    summary_en: null,
    tags: ["portfolio", "ux-research", "internship"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 44,
    hours_ago: 20,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "a2",
    author_id: "p6",
    lang: "en",
    text: "DDD10001 tip: photograph your sketches and sticky-note walls from day one. The folio deadline in week 12 is really a documentation test, and you cannot recreate process photos you never took.",
    tldr: null,
    summary_en: null,
    tags: ["unit-review", "study-tips", "portfolio"],
    unit_codes: ["DDD10001"],
    topic: "unit-review",
    helpful_count: 36,
    hours_ago: 55,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "a3",
    author_id: "p6",
    lang: "en",
    text: "Figma tip that levels up student work instantly: auto layout everything, then set up 4 text styles and 6 colour variables before you design a single screen. Constraints make you faster, not slower.",
    tldr: null,
    summary_en: null,
    tags: ["figma", "ui-design", "study-tips"],
    unit_codes: [],
    topic: "study-tips",
    helpful_count: 57,
    hours_ago: 110,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Minh Le (p7, IT Y1 mentee) ----
  {
    id: "m1",
    author_id: "p7",
    lang: "en",
    text: "Week 4 of COS10009 and arrays finally clicked after I drew them as parking spots on paper. Sharing in case it helps another year 1, because sometimes the dumb analogy is the one that works.",
    tldr: null,
    summary_en: null,
    tags: ["beginners", "study-tips", "python"],
    unit_codes: ["COS10009"],
    topic: "study-tips",
    helpful_count: 29,
    hours_ago: 3,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "m2",
    author_id: "p7",
    lang: "en",
    text: "Is it normal to feel behind in first year? Everyone in my lab seems to have been coding since they were 12 and I started 6 weeks ago. Any seniors been through this?",
    tldr: null,
    summary_en: null,
    tags: ["wellbeing", "beginners"],
    unit_codes: [],
    topic: "wellbeing",
    helpful_count: 48,
    hours_ago: 28,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "m3",
    author_id: "p7",
    lang: "en",
    text: "Built my first ever webpage for a uni task and put it on GitHub Pages. It's just HTML and CSS and it's ugly, but it's MINE and it's live on the internet. Small wins.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/webpage.svg",
    tags: ["web-development", "beginners", "projects"],
    unit_codes: ["COS10026"],
    topic: "projects",
    helpful_count: 61,
    hours_ago: 85,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Lan Pham (p8, Business Y2 mentee) ----
  {
    id: "lp1",
    author_id: "p8",
    lang: "en",
    text: "Exchange application diary, entry 1: the hardest part so far is the unit mapping spreadsheet, not the essays. Start matching your units to the host uni's catalogue MONTHS early. Asking past exchange students for their approved mappings saved me weeks.",
    tldr: null,
    summary_en: null,
    tags: ["exchange", "study-tips", "deadlines"],
    unit_codes: [],
    topic: "study-tips",
    helpful_count: 33,
    hours_ago: 18,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "lp2",
    author_id: "p8",
    lang: "en",
    text: "Has anyone in Business actually done an exchange? I'm torn between semester 1 and semester 2 of third year. I keep hearing semester 2 has better scholarship odds, but it clashes with internship recruiting season. Would really appreciate advice from someone who has been through it.",
    tldr: null,
    summary_en: null,
    tags: ["exchange", "consulting", "international-students"],
    unit_codes: [],
    topic: "careers",
    helpful_count: 21,
    hours_ago: 42,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "lp3",
    author_id: "p8",
    lang: "en",
    text: "Presentation hack from my public speaking elective: record yourself once on your phone before any assessed talk. Painful to watch, instantly fixes the filler words. My ACC10007 pitch went from a credit to a distinction.",
    tldr: null,
    summary_en: null,
    tags: ["presentations", "study-tips"],
    unit_codes: ["ACC10007"],
    topic: "study-tips",
    helpful_count: 27,
    hours_ago: 105,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Tom Baker (p9, CS Y1 mentee) ----
  {
    id: "t1",
    author_id: "p9",
    lang: "en",
    text: "Made Pong in Unity following a YouTube tutorial, then remade it WITHOUT the tutorial. The second time took 3x longer and taught me 10x more. Tutorial hell is real, escape early.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/pong.svg",
    tags: ["game-development", "projects", "beginners"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 39,
    hours_ago: 22,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "t2",
    author_id: "p9",
    lang: "en",
    text: "Anyone know if game dev clubs look at first years? I want to join a jam team but my only finished project is a Pong clone. Do I wait until I'm better or just show up?",
    tldr: null,
    summary_en: null,
    tags: ["game-development", "beginners", "networking"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 18,
    hours_ago: 48,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "t3",
    author_id: "p9",
    lang: "en",
    text: "PSA for COS10009 students: the practice exam on Canvas is from an older curriculum. My tutor said focus on the lab tasks from weeks 8-11 instead. Would've wasted my whole SWOTVAC on the wrong material.",
    tldr: null,
    summary_en: null,
    tags: ["study-tips", "exams", "beginners"],
    unit_codes: ["COS10009"],
    topic: "study-tips",
    helpful_count: 55,
    hours_ago: 68,
    flag_reason: null,
    is_demo: true,
  },

  // ---- Aisha Khan (p10, DS Y2 mentee) ----
  {
    id: "ak1",
    author_id: "p10",
    lang: "en",
    text: "First Kaggle competition done! Finished 412th out of 800 which sounds bad until you realise I couldn't write a groupby without googling it 3 months ago. Writing up my approach this weekend like the seniors suggested.",
    tldr: null,
    summary_en: null,
    tags: ["kaggle", "pandas", "projects"],
    unit_codes: [],
    topic: "projects",
    helpful_count: 42,
    hours_ago: 14,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "ak2",
    author_id: "p10",
    lang: "en",
    text: "SQL study group for COS20015, Thursdays 4pm in the library. We're 4 people working through the Mode tutorial together. Two spots left, reply if keen. Beginners welcome, that's the point.",
    tldr: null,
    summary_en: null,
    tags: ["sql", "study-tips", "networking"],
    unit_codes: ["COS20015"],
    topic: "study-tips",
    helpful_count: 25,
    hours_ago: 38,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "ak3",
    author_id: "p10",
    lang: "en",
    text: "Text me on 0412 345 678 if you want my STA10003 notes, selling the full semester bundle for $50. Also have last year's assignment solutions.",
    tldr: null,
    summary_en: null,
    tags: ["statistics", "notes"],
    unit_codes: ["STA10003"],
    topic: "resources",
    helpful_count: 2,
    hours_ago: 58,
    flag_reason: "Contains personal contact info and offers assignment solutions for sale. Needs human review.",
    is_demo: true,
  },

  // ---- Chris Park (p11, IT Y2 mentee) ----
  {
    id: "c1",
    author_id: "p11",
    lang: "en",
    text: "Passed the CompTIA Security+ while doing TNE10006. The unit content overlaps about 40% so studying for both at once was efficient. Happy to share my study plan mapping unit weeks to exam objectives.",
    tldr: null,
    summary_en: null,
    tags: ["cybersecurity", "certifications", "study-tips"],
    unit_codes: ["TNE10006"],
    topic: "study-tips",
    helpful_count: 34,
    hours_ago: 32,
    flag_reason: null,
    is_demo: true,
  },
  {
    id: "c2",
    author_id: "p11",
    lang: "en",
    text: "Got the exact final exam questions for TNE10006 from someone who sat it last semester, DM me and I'll send them through before Friday.",
    tldr: null,
    summary_en: null,
    tags: ["exams", "networking"],
    unit_codes: ["TNE10006"],
    topic: "study-tips",
    helpful_count: 1,
    hours_ago: 44,
    flag_reason: "Possible sharing of exam questions. Academic integrity concern, needs human review.",
    is_demo: true,
  },

  // ---- Emma Davis (p12, Design Y1 mentee) ----
  {
    id: "e1",
    author_id: "p12",
    lang: "en",
    text: "Redesigned my student club's event poster in Figma using the auto layout tips from a senior here. First time something I made got printed! Posting the before/after to my baby portfolio.",
    tldr: null,
    summary_en: null,
    image_url: "/demo/poster.svg",
    tags: ["figma", "portfolio", "ui-design"],
    unit_codes: ["DDD10001"],
    topic: "projects",
    helpful_count: 31,
    hours_ago: 6,
    flag_reason: null,
    is_demo: true,
  },
];

// Demo replies so unit discussions look alive before anyone types.
export const REPLIES = [
  { id: "r1", post_id: "s2", author_id: "p7", text: "Doing the custom project early saved me too. I started week 3 and still barely finished.", hours_ago: 40 },
  { id: "r2", post_id: "s2", author_id: "p12", text: "Any tips for picking a project scope that isn't too ambitious?", hours_ago: 32 },
  { id: "r3", post_id: "s5", author_id: "p9", text: "Doing every lab twice sounds like a grind but it genuinely works. The exam felt familiar.", hours_ago: 100 },
  { id: "r4", post_id: "d1", author_id: "p10", text: "Wish I had read this in week 1. The recursion week filtered half my friends.", hours_ago: 55 },
  { id: "r5", post_id: "pr1", author_id: "p8", text: "The weekly quizzes carried my grade. Do them the day the content drops.", hours_ago: 70 },
  { id: "r6", post_id: "m1", author_id: "p1", text: "Great writeup. Also: the lab solutions from week 6 onwards reuse earlier patterns, so revising old labs pays twice.", hours_ago: 20 },
  { id: "r7", post_id: "j2", author_id: "p11", text: "How maths-heavy is it really? I keep hearing different things.", hours_ago: 90 },
  { id: "r8", post_id: "j2", author_id: "p4", text: "More logic than maths. If you can follow a budget spreadsheet you can pass.", hours_ago: 85 },
  { id: "r9", post_id: "c1", author_id: "p5", text: "The packet tracer labs are the whole unit. Do not skip them.", hours_ago: 30 },
  { id: "r10", post_id: "a2", author_id: "p6", text: "Auto layout changed my life, glad the tip landed!", hours_ago: 44 },
];

export function getProfile(id) {
  return PROFILES.find((p) => p.id === id) ?? null;
}

export function getPostsByAuthor(authorId) {
  return POSTS.filter((p) => p.author_id === authorId);
}

export function getSeedReplies(postId) {
  return REPLIES.filter((r) => r.post_id === postId);
}
